### ISSUE TITLE
API additions in 1.1.0 -- Tracking Issue

### ISSUE THREAD

**Issue by A248** [A248/LibertyBans#162]
Introduce new API:
* [x] Modify draft punishments before enaction, [#130](https://github.com/A248/LibertyBans/issues/130).
* [x] Expose alt detection, distinguishing between normal and strict links. 
* [x] Change the reason and end time of a punishment. Helps implement [#115](https://github.com/A248/LibertyBans/issues/115).
* [x] Add calculable punishment API based on escalation tracks, along with new events, to implement [#180](https://github.com/A248/LibertyBans/issues/180).
* [x] Purge a punishment completely, to implement [#119](https://github.com/A248/LibertyBans/issues/119).
* [x] Add target username in `PostPunishEvent`/`PostPardonEvent` if available [#76](https://github.com/A248/LibertyBans/issues/76).

Expand selection APIs:
* Add more capabilities to SelectionOrderBuilder:
  * [x] Select punishments before a given time, [#161](https://github.com/A248/LibertyBans/issues/161).
  * [x] Select number of punishments without retrieving their details, [#158](https://github.com/A248/LibertyBans/issues/158).
  * [x] Filter victim types in SelectionOrderBuilder, not just victims. Helps implement Sponge's BanService if configured, see [#99](https://github.com/A248/LibertyBans/issues/99).
* [x] Add complementary selection API to retrieve applicable punishments:
  * Select all applicable punishments for a given user. Improves `/checkuser` addon's efficiency.
  * Select historical applicable punishments. Assists [#157](https://github.com/A248/LibertyBans/issues/157).
* [x] Define ordering of returned punishments:
  * This logical API addition gives callers flexibility and is a convenient way to unify the implementation, which will fork based on the two selection APIs, selecting traditionally and selecting by applicability.
  * ~~Also add the ability to select one punishment per type, with the prioritization determined by the desired ordering.~~

Other:
* [x] Affirm a special property of PunishmentSelector#getApplicablePunishment, [#145](https://github.com/A248/LibertyBans/issues/145).
* [x] Guarantee the availability of cached mutes on Bukkit and Spigot with regard to PunishmentSelector#getCachedMute.
* [x] Review and expand scope API as will likely be necessary, [#146](https://github.com/A248/LibertyBans/issues/146).
